<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="gazmeeva-s" name="Default test" tests="2" failures="2" timestamp="25 Dec 2014 12:07:14 GMT" time="19.164" errors="0">
  <testcase name="testAddressCreationwithValidData" time="5.838" classname="com.example.tests.AdressCreateTest">
    <failure type="java.lang.AssertionError" message="Lists differ at element [28]: AddressDate [fname=, lastname=test844451170, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] != AddressDate [fname=, lastname=test59885026, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] expected [AddressDate [fname=, lastname=test844451170, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]] but found [AddressDate [fname=, lastname=test59885026, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [28]: AddressDate [fname=, lastname=test844451170, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] != AddressDate [fname=, lastname=test59885026, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] expected [AddressDate [fname=, lastname=test844451170, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]] but found [AddressDate [fname=, lastname=test59885026, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAddressCreationwithValidData -->
  <testcase name="testAddressCreationwithValidData" time="5.311" classname="com.example.tests.AdressCreateTest">
    <failure type="java.lang.AssertionError" message="Lists differ at element [21]: AddressDate [fname=, lastname=test1141668914, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] != AddressDate [fname=, lastname=test-466624878, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] expected [AddressDate [fname=, lastname=test1141668914, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]] but found [AddressDate [fname=, lastname=test-466624878, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [21]: AddressDate [fname=, lastname=test1141668914, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] != AddressDate [fname=, lastname=test-466624878, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=] expected [AddressDate [fname=, lastname=test1141668914, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]] but found [AddressDate [fname=, lastname=test-466624878, address=, home=, mobile=, work=, email=, email2=, bday=, bmonth=, byear=, groupdate=, address2=, phone2=]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAddressCreationwithValidData -->
</testsuite> <!-- Default test -->
