<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="6" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20802" started-at="2014-12-25T08:07:37Z" finished-at="2014-12-25T08:07:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20802" started-at="2014-12-25T08:07:37Z" finished-at="2014-12-25T08:07:58Z">
      <class name="com.example.tests.AdressCreateTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="setUp" is-config="true" duration-ms="10990" started-at="2014-12-25T11:07:37Z" finished-at="2014-12-25T11:07:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testAddressCreationwithValidData(com.example.tests.AddressDate)[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="testAddressCreationwithValidData" duration-ms="1230" started-at="2014-12-25T11:07:48Z" data-provider="randomValidAddressGenerator" finished-at="2014-12-25T11:07:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AddressDate [fname=test-371018593, lastname=test-1521803161, address=test-1172400730, home=test1643401811, mobile=test342086524, work= , email=test1706027240, email2=test869822161, bday=null, bmonth=null, byear=null, groupdate=null, address2=test432865152, phone2=test892844890]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(Unknown Source)
	at com.example.fw.AddressHelper.GetAddress(AddressHelper.java:101)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddressCreationwithValidData -->
        <test-method status="FAIL" signature="testAddressCreationwithValidData(com.example.tests.AddressDate)[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="testAddressCreationwithValidData" duration-ms="1127" started-at="2014-12-25T11:07:50Z" data-provider="randomValidAddressGenerator" finished-at="2014-12-25T11:07:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AddressDate [fname= , lastname=test603211368, address=test162881811, home=test-975621439, mobile=test-1744882681, work=test1983960504, email=test419465675, email2= , bday=null, bmonth=null, byear=null, groupdate=null, address2= , phone2=test-386622879]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(Unknown Source)
	at com.example.fw.AddressHelper.GetAddress(AddressHelper.java:101)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddressCreationwithValidData -->
        <test-method status="FAIL" signature="testAddressCreationwithValidData(com.example.tests.AddressDate)[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="testAddressCreationwithValidData" duration-ms="795" started-at="2014-12-25T11:07:51Z" data-provider="randomValidAddressGenerator" finished-at="2014-12-25T11:07:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AddressDate [fname=test-678093792, lastname= , address=test-74771888, home=test-958388052, mobile=test161110853, work=test-946320239, email= , email2=test626546541, bday=null, bmonth=null, byear=null, groupdate=null, address2= , phone2= ]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(Unknown Source)
	at com.example.fw.AddressHelper.GetAddress(AddressHelper.java:101)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddressCreationwithValidData -->
        <test-method status="FAIL" signature="testAddressCreationwithValidData(com.example.tests.AddressDate)[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="testAddressCreationwithValidData" duration-ms="799" started-at="2014-12-25T11:07:51Z" data-provider="randomValidAddressGenerator" finished-at="2014-12-25T11:07:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AddressDate [fname= , lastname= , address= , home= , mobile= , work=test1718971897, email=test1054768246, email2=test-954415148, bday=null, bmonth=null, byear=null, groupdate=null, address2= , phone2= ]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(Unknown Source)
	at com.example.fw.AddressHelper.GetAddress(AddressHelper.java:101)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddressCreationwithValidData -->
        <test-method status="FAIL" signature="testAddressCreationwithValidData(com.example.tests.AddressDate)[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="testAddressCreationwithValidData" duration-ms="881" started-at="2014-12-25T11:07:52Z" data-provider="randomValidAddressGenerator" finished-at="2014-12-25T11:07:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[AddressDate [fname=test-742789923, lastname=test937862639, address= , home= , mobile= , work=test-569059972, email=test1127799800, email2= , bday=null, bmonth=null, byear=null, groupdate=null, address2=test-1170594467, phone2= ]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(Unknown Source)
	at com.example.fw.AddressHelper.GetAddress(AddressHelper.java:101)
	at com.example.tests.AdressCreateTest.testAddressCreationwithValidData(AdressCreateTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddressCreationwithValidData -->
        <test-method status="PASS" signature="testEmptyPhoneCreation()[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="testEmptyPhoneCreation" duration-ms="4413" started-at="2014-12-25T11:07:53Z" finished-at="2014-12-25T11:07:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEmptyPhoneCreation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.AdressCreateTest@2d6d8735]" name="tearDown" is-config="true" duration-ms="538" started-at="2014-12-25T11:07:58Z" finished-at="2014-12-25T11:07:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.AdressCreateTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
